#yml(yaml)文件配置方式
#1、属性配置
name: zhangsan
#2、对象配置
person:
  name: zhangsan
  age: 18
  address: beijing
#配置文件加载优先级application.yml,application.yaml,application.properties，后面加载的属性会覆盖前面加载的属性
server:
  port: 8082
#行内配置
student: {name: zhangsan, age: 18, address: beijing}
#3、数据集合配置
city:
  - beijing
  - nanjing
  - dongjing
#行内配置
city: [beijing, nanjing, dongjing]
#4、对象集合配置,例如：学生集合
student:
  - name: lisi
    age: 18
    address: nanjing
  - name: wangwu
    age: 17
    address: dongjing
#行内配置
student: [{name: lisi, age: 18, address: nanjing}, {name: wangwu, age: 17, address: dongjing}]
#5、Map配置(跟对象配置一样)
map:
  key1: value1
  key2: value2